@root_url = http://localhost:5263

GET {{root_url}}/Home
Accept: application/json
###

GET {{root_url}}/API/Rooms
Accept: application/json
###

GET {{root_url}}/Restaurant/Menu/Pizzas/MenuItems
Accept: application/json
###

DELETE {{root_url}}/API/Users/Delete/kian
Accept: application/json
###

GET {{root_url}}/API/HouseKeeping/Employee
Accept: application/json
###

GET {{root_url}}/API/HouseKeeping
Accept: application/json
###

GET {{root_url}}/API/Maintenance
Accept: application/json
###

GET {{root_url}}/API/Maintenance/kkk
Accept: application/json
###