@root_url = http://localhost:5263

GET {{root_url}}/Home
Accept: application/json
###

GET {{root_url}}/API/Service/AllServiceUsages
Accept: application/json
###

POST {{root_url}}/API/Users/Employees
Content-Type: application/json
Accept: application/json

{
  "userName": "john_doe",
  "password": "P@ssw0rd123",
  "email": "john.doe@example.com",
  "roleId": 1,
  "birthDate": "1998-05-14",
  "salary": 55000,
  "departmentId": 2,
  "position": "intern"
}
###

POST {{root_url}}/API/Restaurant/Orders
Content-Type: application/json
Accept: application/json

{
  "tableId": 1,
  "status": "Pending",
  "orderItems": [
    {
      "itemId": 1,
      "quantity": 2
    },
    {
      "itemId": 2,
      "quantity": 1
    },
    {
      "itemId": 3,
      "quantity": 3
    },
    {
      "itemId": 4,
      "quantity": 1
    },
    {
      "itemId": 5,
      "quantity": 2
    }
  ]
}