@root_url = http://localhost:5263

GET {{root_url}}/Home
Accept: application/json
###

GET {{root_url}}/API/Service/GuestUsed/kian
Accept: application/json
###

GET {{root_url}}/Restaurant/Menu/Pizzas/MenuItems
Accept: application/json
###

DELETE {{root_url}}/API/Users/Delete/kian
Accept: application/json
###

POST {{root_url}}/API/Restaurant/Menu/Categories
Content-Type: application/json
Accept: application/json

{
  "name": "aba"
}
###

POST {{root_url}}/API/Restaurant/Menu/Pizzas/MenuItems
Content-Type: application/json
Accept: application/json

{
  "name": "Pepperoni Pizza",
  "description": "Classic pepperoni with mozzarella",
  "price": 12.12
}